In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import FunctionTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
import scipy.stats as stats
import os
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load data

In [ ]:
folder_path = 'Data'
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

run_df = pd.DataFrame()
walk_df = pd.DataFrame()

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    if 'Run' in file:
        temp_df = pd.read_csv(file_path)
        run_df = pd.concat([run_df, temp_df], ignore_index=True)
    elif 'Walk' in file:
        temp_df = pd.read_csv(file_path)
        walk_df = pd.concat([walk_df, temp_df], ignore_index=True)

fig1 = plt.figure(figsize=(10, 10))
ax = fig1.add_subplot(111, projection='3d')

sc1 = ax.scatter(walk_df['ax'], walk_df['ay'], walk_df['az'], c=walk_df['time'], cmap='viridis',marker='o', s=1)
#ax.scatter(run_df['ax'], run_df['ay'], run_df['az'], c=run_df['time'], cmap='viridis',marker='.', s=0.75)

cbar1 = plt.colorbar(sc1, ax=ax, pad=0.1)
cbar1.set_label('Time')
#ax.scatter(walk_df['ax'], walk_df['ay'], walk_df['az'], c='r', marker='.', s=0.75)
#ax.scatter(run_df['ax'], run_df['ay'], run_df['az'], c='b', marker='.', s=0.75)

ax.set_title('Walk accelerate')
ax.set_xlabel('Ax')
ax.set_ylabel('Ay')
ax.set_zlabel('Az')

plt.show(fig1)

In [ ]:
fig2 = plt.figure(figsize=(10, 10))
ax = fig2.add_subplot(111, projection='3d')

#sc1 = ax.scatter(walk_df['ax'], walk_df['ay'], walk_df['az'], c=walk_df['time'], cmap='viridis',marker='o', s=1)
sc2 = ax.scatter(run_df['ax'], run_df['ay'], run_df['az'], c=run_df['time'], cmap='viridis',marker='o', s = 1)

cbar1 = plt.colorbar(sc2, ax=ax, pad=0.1)
cbar1.set_label('Time')
#ax.scatter(walk_df['ax'], walk_df['ay'], walk_df['az'], c='r', marker='.', s=0.75)
#ax.scatter(run_df['ax'], run_df['ay'], run_df['az'], c='b', marker='.', s=0.75)


ax.set_xlabel('Ax')
ax.set_ylabel('Ay')
ax.set_zlabel('Az')

plt.show(fig2)

In [42]:
dfs_combined = pd.concat([run_df, walk_df], ignore_index=True)
X = dfs_combined[['ax','ay','az','speed']]

le = LabelEncoder()
y = le.fit_transform(dfs_combined['label'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


pandas.core.frame.DataFrame

# Training + StandardScaler - dataclean

In [43]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## MLP

In [44]:
model_nn = MLPClassifier(
        solver = 'adam', hidden_layer_sizes=(16,32,64), activation='relu'
    )

model_nn.fit(X_train_scaled, y_train)
y_pred_nn = model_nn.predict(X_test_scaled)

# Evaluate the model
accuracy_nn = accuracy_score(y_test, y_pred_nn)
print(f"Accuracy: {accuracy_nn:.2f}")

# Print confusion matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_nn))

Accuracy: 0.97

Confusion Matrix:
[[1297   62]
 [   6 1139]]


C:\Users\lhg45\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


## Gaussian Naive Bayes

In [45]:
model_NB =  GaussianNB()
model_NB.fit(X_train_scaled, y_train)
y_pred_NB = model_NB.predict(X_test_scaled)

# Evaluate the model
accuracy_NB = accuracy_score(y_test, y_pred_NB)
print(f"Accuracy: {accuracy_NB:.2f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_NB))

Accuracy: 0.95

Confusion Matrix:
[[1266   93]
 [  44 1101]]


## K-Nearest Neighbors Classifier

In [46]:
model_knn = KNeighborsClassifier(n_neighbors=10)
model_knn.fit(X_train_scaled, y_train)
y_pred_knn = model_knn.predict(X_test_scaled)

# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"Accuracy: {accuracy_knn:.2f}")

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

Accuracy: 0.97

Confusion Matrix:
[[1293   66]
 [  17 1128]]


## Random Forest Classifier

In [47]:
model_RF = RandomForestClassifier(n_estimators=150, random_state=42)

model_RF.fit(X_train_scaled, y_train)
y_pred_RF = model_RF.predict(X_test_scaled)

# Evaluate the model
accuracy_RF = accuracy_score(y_test, y_pred_RF)
print(f"Accuracy: {accuracy_RF:.2f}")

# Print confusion matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_RF))

Accuracy: 0.99

Confusion Matrix:
[[1345   14]
 [   6 1139]]
